[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "orderbook/=contracts/orderbook",
    "test-helpers/=test/helpers",
    "mocks/=test/mocks",
    "nfts/=periphery/nfts",
    "dev/=script/dev",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
