[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "orderbook/=contracts/orderbook",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts"
]

[lint]
exclude_lints = ["unaliased-plain-import"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
