[31337]
endpoint_url = "http://localhost:8545"

[31337.address]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
order_engine = "0xFd6Fa56FcF2F2f03d0026D9211E77D739A34F9F2"
nft_c_0 = "0x2d929838d32Ea33a0994D37F82965C2d284E3b4F"
nft_c_1 = "0xF373BeF9a4F9AE4e101349477e348A700Bca90Db"

[31337.uint]
nft_c_count = 2
pipeline_start_ts = 1768430783
pipeline_end_ts = 1770849994
fork_start_block = 24236020
