[31337]
endpoint_url = "http://localhost:8545"

[31337.address]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
order_engine = "0x680D7aB71dB31610dE7A6ab07c848821E3bFD84f"
nft_c_0 = "0x480ce59387443A9Bf266a4657f0E2AE1E6a7B771"
nft_c_1 = "0x68B5f6a7ccD9EA0642d7B069135d84AD2CC26232"

[31337.uint]
nft_c_count = 2
pipeline_start_ts = 1769205587
pipeline_end_ts = 1771624804
fork_start_block = 24300328
