[31337]
endpoint_url = "http://localhost:8545"

[31337.address]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
order_engine = "0x68B5f6a7ccD9EA0642d7B069135d84AD2CC26232"
nft_c_0 = "0xB133BC21277883faD2B2e3c952fC817FdE7DbacC"
nft_c_1 = "0x49e6bBc93948E1EaeBd5EFE0005213F3D70363c0"

[31337.uint]
nft_c_count = 2
pipeline_start_ts = 1769255567
pipeline_end_ts = 1771674775
fork_start_block = 24304479
