[31337]
endpoint_url = "http://localhost:8545"

[31337.address]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
order_engine = "0x10FcD639d832188e94c50eD1C4C3A9F6403a0a64"
nft_c_0 = "0x0b4868Dbdfb981a4b26eE5d670739Bc03b16cd9c"
nft_c_1 = "0xA96658Fc034490F0E537bAC43ba48efE0B1C57e3"

[31337.uint]
nft_c_count = 2
pipeline_start_ts = 1767744743
pipeline_end_ts = 1770163957
fork_start_block = 24179141
