[31337]
endpoint_url = "http://localhost:8545"

[31337.address]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
order_engine = "0x71498Ed008E4C968551e26eB4B803631241B5D26"
nft_c_0 = "0x751527acFf86638af877D292Ef165300D9AdDd1E"
nft_c_1 = "0x3b0f2B6485b9C16B28b268a2CEef5BD7231FFB4d"

[31337.uint]
pipeline_start_ts = 1766023739
pipeline_end_ts = 1768442951
fork_start_block = 24036409
nft_c_count = 2
