[31337]
endpoint_url = "http://localhost:8545"

[31337.address]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
order_engine = "0xa45583B27beAc8a0091A25588e64a0f49De6D61e"
nft_c_0 = "0x6F31ECf7D6a8aa3a0A6748FCaC25f213fF29EFe4"
nft_c_1 = "0x2374d9E21d3be247DA71307fc661076DDDe400ef"

[31337.uint]
nft_c_count = 2
pipeline_start_ts = 1767313619
pipeline_end_ts = 1769732823
fork_start_block = 24143355
